= API Types
:source-highlighter: pygments
:source-language: json
:source-linenums-option:
:pygments-style: paraiso-dark
:toc: left
:toc-title:
:icons: font
:sectlinks:
:stylesheet: asciidoctor.css
:prewrap!:
Elizabeth Paige Harper <eph@softask.app>
v1.0.0


== Auth Types

https://softask-app.github.io/api-types/v1/types/auth/auto-token.json[`auth/auto-token`]::
Auto-Auth token.
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/auth/auto-token.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/auth/auth-body.json[`auth/auth-body`]::
Successful authentication response body.
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/auth/auth-body.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/auth/device-payload.json[`auth/device-payload`]::
Device auto-auth payload.
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/auth/device-payload.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/auth/webapp-payload.json[`auth/webapp-payload`]::
Web app auth payload.
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/auth/webapp-payload.json[]
----
====
endif::[]

== Common Types

https://softask-app.github.io/api-types/v1/types/meta/api-key.json[`meta/api-key`]::
API auth token.
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/meta/api-key.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/meta/date-time.json[`meta/date-time`]::
RFC3339 timestamp.
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/meta/date-time.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/meta/request-id.json[`meta/request-id`]::
Unique request ID.
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/meta/request-id.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/pg/serial8.json[`pg/serial8`]::
Postgres `BIGSERIAL` type.  Used for record IDs.
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/pg/serial8.json[]
----
====
endif::[]

== Error Types

https://softask-app.github.io/api-types/v1/types/error/400.json[`error/400`]::
{empty}
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/error/400.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/error/401.json[`error/401`]::
{empty}
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/error/401.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/error/403.json[`error/403`]::
{empty}
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/error/403.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/error/404.json[`error/404`]::
{empty}
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/error/404.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/error/405.json[`error/405`]::
{empty}
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/error/405.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/error/429.json[`error/429`]::
{empty}
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/error/429.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/error/500.json[`error/500`]::
{empty}
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/error/500.json[]
----
====
endif::[]


== Device Types

https://softask-app.github.io/api-types/v1/types/device/device-id.json[`device/device-id`]::
{empty}
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/device/device-id.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/device/full.json[`device/full`]::
{empty}
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/device/full.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/device/trust.json[`device/trust`]::
Device trust response body.
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/device/trust.json[]
----
====
endif::[]


== Task Types

https://softask-app.github.io/api-types/v1/types/task/full.json[`task/full`]::
A full/extended task object.
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/task/full.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/task/short.json[`task/short`]::
An abbreviated task object.
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/task/short.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/task/new.json[`task/new`]::
Task creation payload.
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/task/new.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/task/step/full.json[`task/step/full`]::
A full/extended step object.
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/task/step/full.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/task/step/short.json[`task/step/short`]::
An abbreviated step object.
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/task/step/short.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/task/name.json[`task/name`]::
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/task/name.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/task/tag.json[`task/tag`]::
{empty}
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/task/tag.json[]
----
====
endif::[]

== User Types

https://softask-app.github.io/api-types/v1/types/user/full.json[`user/full`]::
A full/extended user object.
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/user/full.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/user/short.json[`user/short`]::
An abbreviated user object.
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/user/short.json[]
----
====
endif::[]

https://softask-app.github.io/api-types/v1/types/user/new.json[`user/new`]::
User creation payload.
ifndef::env-github[]
+
.Source
[%collapsible]
====
[source]
----
include::types/user/new.json[]
----
====
endif::[]
